# Generated by Django 5.1.5 on 2026-09-08 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('vehicle_number', models.CharField(db_index=True, max_length=30, verbose_name='Номер машины')),
                ('vehicle_number_search', models.CharField(db_index=True, editable=False, max_length=30, verbose_name='Номер для поиска')),
                ('dispatched_at', models.DateTimeField(db_index=True, verbose_name='Время отправления')),
                ('deadline_at', models.DateTimeField(db_index=True, verbose_name='Плановое прибытие')),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Фактическое прибытие')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отмены')),
                ('planned_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Плановая длительность, мин')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('IN_TRANSIT', 'В пути'), ('ARRIVED', 'Прибыл'), ('CANCELLED', 'Отменён')], db_index=True, default='CREATED', max_length=12, verbose_name='Статус')),
                ('dispatch_comment', models.TextField(blank=True, verbose_name='Комментарий при отправлении')),
                ('receive_comment', models.TextField(blank=True, verbose_name='Комментарий при приёме')),
                ('cancel_comment', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('deadline_passed_logged', models.BooleanField(default=False, editable=False, verbose_name='Просрочка зафиксирована в истории')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Отменил')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
                ('point_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='points.point', verbose_name='Точка отправления')),
                ('point_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='points.point', verbose_name='Точка прибытия')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'db_table': 'deliveries',
                'ordering': ('-dispatched_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Рейс создан'), ('DISPATCHED', 'Машина отправлена'), ('EXPENSE_ADDED', 'Добавлен расход'), ('EXPENSE_UPDATED', 'Изменён расход'), ('EXPENSE_DELETED', 'Удалён расход'), ('DEADLINE_PASSED', 'Срок прибытия истёк'), ('RECEIVED', 'Прибытие подтверждено'), ('CANCELLED', 'Рейс отменён'), ('COMMENT_ADDED', 'Добавлен комментарий'), ('UPDATED', 'Рейс изменён')], max_length=20, verbose_name='Тип события')),
                ('event_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время события')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Доп. данные')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.delivery', verbose_name='Рейс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Событие рейса',
                'verbose_name_plural': 'История рейсов',
                'db_table': 'delivery_events',
                'ordering': ('event_time', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'deadline_at'], name='deliveries_status_ef364f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['vehicle_number_search', '-dispatched_at'], name='deliveries_vehicle_673b83_idx'),
        ),
    ]
