# Generated by Django 5.1.5 on 2026-09-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Рейс создан'), ('DISPATCHED', 'Машина отправлена'), ('EXPENSE_ADDED', 'Добавлен расход'), ('EXPENSE_UPDATED', 'Изменён расход'), ('EXPENSE_DELETED', 'Удалён расход'), ('DEADLINE_PASSED', 'Срок прибытия истёк'), ('WAYPOINT_PASSED', 'Пройдена промежуточная точка'), ('RECEIVED', 'Прибытие подтверждено'), ('CANCELLED', 'Рейс отменён'), ('COMMENT_ADDED', 'Добавлен комментарий'), ('UPDATED', 'Рейс изменён')], max_length=20, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='DeliveryWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в маршруте')),
                ('passed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прохождения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='deliveries.delivery', verbose_name='Рейс')),
                ('passed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passed_waypoints', to=settings.AUTH_USER_MODEL, verbose_name='Отметил прохождение')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waypoints', to='points.point', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Промежуточная точка',
                'verbose_name_plural': 'Промежуточные точки',
                'db_table': 'delivery_waypoints',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('delivery', 'point'), name='uniq_waypoint_point_per_delivery')],
            },
        ),
    ]
