# Generated by Django 5.1.5 on 2026-09-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('LOGIN', 'Вход в систему'), ('BLOCK', 'Блокировка'), ('UNBLOCK', 'Разблокировка')], max_length=20, verbose_name='Действие')),
                ('entity_type', models.CharField(db_index=True, max_length=50, verbose_name='Тип объекта')),
                ('entity_id', models.CharField(db_index=True, max_length=50, verbose_name='ID объекта')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Было')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Стало')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'db_table': 'audit_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx')],
            },
        ),
    ]
