# Generated by Django 5.1.5 on 2026-09-08 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_payer_enabled', models.BooleanField(default=False, verbose_name='Правило включено')),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=50, max_digits=12, verbose_name='Порог суммы')),
                ('threshold_currency', models.CharField(choices=[('USD', 'Доллар США'), ('KGS', 'Сом'), ('CNY', 'Юань'), ('RUB', 'Рубль'), ('KZT', 'Тенге')], default='USD', max_length=3, verbose_name='Валюта порога')),
                ('payer_above', models.CharField(choices=[('COMPANY', 'Наша компания'), ('CHINA', 'Китай'), ('DRIVER', 'Водитель'), ('OTHER', 'Другое')], default='CHINA', max_length=10, verbose_name='Плательщик при превышении порога')),
                ('payer_below', models.CharField(choices=[('COMPANY', 'Наша компания'), ('CHINA', 'Китай'), ('DRIVER', 'Водитель'), ('OTHER', 'Другое')], default='COMPANY', max_length=10, verbose_name='Плательщик до порога')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки расходов',
                'verbose_name_plural': 'Настройки расходов',
                'db_table': 'expense_settings',
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип расхода',
                'verbose_name_plural': 'Типы расходов',
                'db_table': 'expense_types',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('USD', 'Доллар США'), ('KGS', 'Сом'), ('CNY', 'Юань'), ('RUB', 'Рубль'), ('KZT', 'Тенге')], db_index=True, default='USD', max_length=3, verbose_name='Валюта')),
                ('payer', models.CharField(choices=[('COMPANY', 'Наша компания'), ('CHINA', 'Китай'), ('DRIVER', 'Водитель'), ('OTHER', 'Другое')], db_index=True, default='COMPANY', max_length=10, verbose_name='Плательщик')),
                ('payer_auto_assigned', models.BooleanField(default=False, verbose_name='Плательщик определён правилом')),
                ('description', models.CharField(max_length=255, verbose_name='Описание расхода')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='deliveries.delivery', verbose_name='Рейс')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensetype', verbose_name='Тип расхода')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'db_table': 'expenses',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['delivery', '-created_at'], name='expenses_deliver_211150_idx')],
            },
        ),
    ]
