# Generated by Django 5.1.5 on 2026-09-09 08:59

from django.db import migrations, models


def drop_unused_rates(apps, schema_editor):
    """Убирает курсы валют, которые больше не используются."""
    CurrencyRate = apps.get_model("expenses", "CurrencyRate")
    CurrencyRate.objects.exclude(code__in=["USD", "KGS"]).delete()


def noop(apps, schema_editor):
    """Обратной операции нет: курсы вернутся значениями по умолчанию."""


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_currencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='code',
            field=models.CharField(choices=[('USD', 'Доллар США'), ('KGS', 'Сом')], max_length=3, unique=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'Доллар США'), ('KGS', 'Сом')], db_index=True, default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='expensesettings',
            name='threshold_currency',
            field=models.CharField(choices=[('USD', 'Доллар США'), ('KGS', 'Сом')], default='USD', max_length=3, verbose_name='Валюта порога'),
        ),
            migrations.RunPython(drop_unused_rates, noop),
    ]
