# Generated by Django 5.1.5 on 2026-09-08 10:00

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('password', models.CharField(db_column='password_hash', max_length=128, verbose_name='Хеш пароля')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('login', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Логин')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('EMPLOYEE', 'Сотрудник')], default='EMPLOYEE', max_length=10, verbose_name='Роль')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ в админку')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'users',
                'ordering': ('full_name',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
